"""empty message

Revision ID: 49735c58e704
Revises: 4deecf55372a
Create Date: 2023-01-19 22:58:09.572942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49735c58e704'
down_revision = '4deecf55372a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('textfile',
    sa.Column('textfile_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=False),
    sa.Column('update_feed', sa.Boolean(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('textfile_id')
    )
    op.drop_table('text_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_file',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('update_feed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='text_file_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('textfile')
    # ### end Alembic commands ###
