"""empty message

Revision ID: 4deecf55372a
Revises: dba570502117
Create Date: 2023-01-14 12:57:40.558143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4deecf55372a'
down_revision = 'dba570502117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=False),
    sa.Column('update_feed', sa.Boolean(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_file')
    # ### end Alembic commands ###
