"""empty message

Revision ID: 85f9ef821076
Revises: dd03c3657a9b
Create Date: 2022-07-24 23:18:14.368782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f9ef821076'
down_revision = 'dd03c3657a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('salt', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'salt')
    # ### end Alembic commands ###
