"""empty message

Revision ID: c05f74e8449a
Revises: 49735c58e704
Create Date: 2023-01-21 20:53:48.673697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c05f74e8449a'
down_revision = '49735c58e704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('roles', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('person')
    with op.batch_alter_table('textfile', schema=None) as batch_op:
        batch_op.drop_constraint('textfile_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'person_account', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('textfile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('textfile_ibfk_1', 'person', ['owner_id'], ['id'])

    op.create_table('person',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('roles', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    op.drop_table('person_account')
    # ### end Alembic commands ###
