"""empty message

Revision ID: dba570502117
Revises: 85f9ef821076
Create Date: 2022-07-25 11:24:11.892170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dba570502117'
down_revision = '85f9ef821076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='person')
    op.drop_column('person', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
    op.create_index('username', 'person', ['username'], unique=False)
    # ### end Alembic commands ###
