"""empty message

Revision ID: dd03c3657a9b
Revises: abd8aaee887a
Create Date: 2022-07-23 16:47:35.267303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd03c3657a9b'
down_revision = 'abd8aaee887a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('roles', sa.Integer(), nullable=False))
    op.add_column('person', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('person', 'password_salt')
    op.drop_column('person', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('person', sa.Column('password_salt', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('person', 'password')
    op.drop_column('person', 'roles')
    # ### end Alembic commands ###
